name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    env:
      DOCKER_CONTAINER_REGISTRY: groffegithubactions.azurecr.io
      NOME_IMAGEM: $DOCKER_CONTAINER_REGISTRY/apicontagemk8s
      PATH_PROJETO: ./APIContagem
      AZURE_RESOURCE_GROUP_K8S: TesteKubernetes
      AZURE_CLUSTER_K8S: AKSCluster
      NAMESPACE_K8S: dedalus3
      DEPLOYMENT_K8S: apicontagemk8s

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Teste nome imagem
      run: echo ${{ env.NOME_IMAGEM }}

    - name: Teste senha Registry
      run: echo ${{ secrets.DOCKER_PASSWORD }}

    - name: Login no Azure Container Registry
      uses: Azure/docker-login@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        login-server: ${{ env.DOCKER_CONTAINER_REGISTRY }}
      
    - name: Build e Push no Azure Container Registry
      run: |
        cd ${{ env.PATH_PROJETO }}
        docker build . --file Dockerfile --tag ${{ env.NOME_IMAGEM }}:$GITHUB_RUN_NUMBER
        docker tag ${{ env.NOME_IMAGEM }}:$GITHUB_RUN_NUMBER ${{ env.NOME_IMAGEM }}:latest
        docker push ${{ env.NOME_IMAGEM }}
        
    - name: Azure Kubernetes Service - set context - Conectando ao cluster
      uses: Azure/aks-set-context@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }} 
        resource-group: ${{ env.AZURE_RESOURCE_GROUP_K8S }}
        cluster-name:  ${{ env.AZURE_CLUSTER_K8S }}

    - name: Azure Kubernetes Service - Criando Secret para acesso ao Container Registry
      uses: Azure/k8s-create-secret@v1
      with:
        namespace: ${{ env.NAMESPACE_K8S }}
        container-registry-url: ${{ env.DOCKER_CONTAINER_REGISTRY }}
        container-registry-username: ${{ secrets.DOCKER_USERNAME }}
        container-registry-password: ${{ secrets.DOCKER_PASSWORD }}
        secret-name: webapp-k8s-secret

    - name: kubectl - Exibindo a versão
      run: kubectl version

    - name: kubectl - Removendo o Deployment caso exista
      run: kubectl delete deployment --ignore-not-found ${{ env.DEPLOYMENT_K8S }} -n ${{ env.NAMESPACE_K8S }}

    - name: Azure Kubernetes Service - Deployment de Web App
      uses: Azure/k8s-deploy@v1
      with:
        namespace: ${{ env.NAMESPACE_K8S }}
        manifests: |
          manifests/deployment.yml
          manifests/service.yml
        images: |
          ${{ env.NOME_IMAGEM }}:latest
        imagepullsecrets: |
          webapp-k8s-secret
